### PR TITLE
fix(passwords): No more false positives!

### LINKED ISSUE #5: False positive rate is quite high
Firstly - thanks for the library! I couldn't find a common password library for node that's being actively maintained.

If I have my maths right (and experimentally it seems to be about right), setting the number of bits to 10 times the number of passwords in the bloom filter will result in a false positive rate of just under 1% given you're using 8 hashes. This feels a little high for the use case of password strength checking - quite a lot of strong passwords will be rejected seemingly inexplicably. 

Would you be open to increasing the value here and rebuilding the bloom filters?

https://github.com/mozilla/fxa-common-password-list/blob/master/scripts/plaintext2bloom.js#L22

(I've built my own bloom filters for my application now using your code - more just thinking for future people who come across the library)

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Ditch the bloomfilter, use incremental (front) encoding instead.

This results in a slightly larger library, but no false
positives.

See https://en.wikipedia.org/wiki/Incremental_encoding for more.

@mozilla/fxa-devs - r?

issue mozilla/fxa#1530
fixes #5

### CODE REVIEW

**Review by chenba — APPROVED** [review]
LGTM

File: scripts/generate-encoded-passwords-module.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+const passwords = readPasswords(inputFilename, minLength, numberOfPasswords);
+const encoder = new Encoder();
+const encodedPasswords = encoder.encode(passwords);
+
+/*eslint-disable no-console*/
+console.log('/* This Source Code Form is subject to the terms of the Mozilla Public');
+console.log(' * License, v. 2.0. If a copy of the MPL was not distributed with this');
+console.log(' * file, You can obtain one at http://mozilla.org/MPL/2.0/. */');
+console.log('');
+console.log(`module.exports = \`${encodedPasswords.join('\n')}\`;\n`);
```
Comment (chenba) [inline scripts/generate-encoded-passwords-module.js]: Was there a particular reason for console.log instead of writing to a file?  Just curious.

Comment (shane-tomlinson) [reply scripts/generate-encoded-passwords-module.js]: The only reason I could think of is it's nice to be able to use unix tools on output, but that's not really a strong reason here. I can change it to write directly to a file instead.
